/*
 * COPYRIGHT:
 *
 * TITLE TO THE CODE REMAIN WITH ZEB/INFORMATION.TECHNOLOGY. THE CODE IS COPYRIGHTED AND PROTECTED BY LAW. YOU WILL NOT
 * REMOVE ANY COPYRIGHT NOTICE FROM THE CODE. REASSEMBLING, RECOMPILATION, TRANSFER, DISTRIBUTION OR MODIFICATION OF
 * PART OR ALL OF THE CODE IN ANY FORM WITHOUT THE PRIOR WRITTEN PERMISSION OF ZEB/INFORMATION.TECHNOLOGY IS PROHIBITED.
 *
 * created: 27.03.2023 - 14:18:21
 */
package de.zeb.lowcode.generator.domain.maske.typescript;

/**
 * @author dkleine Definiert, von wo ein Aufrufer einen Import haben möchte
 */
public enum EnumImport {

    TYPE,
    TYPE_CHECK_OPTIONAL,
    TYPE_CHECK_REQUIRED,
    TYPE_REFERENCE;
}
