/*
 * COPYRIGHT:
 *
 * TITLE TO THE CODE REMAIN WITH ZEB/INFORMATION.TECHNOLOGY. THE CODE IS COPYRIGHTED AND PROTECTED BY LAW. YOU WILL NOT
 * REMOVE ANY COPYRIGHT NOTICE FROM THE CODE. REASSEMBLING, RECOMPILATION, TRANSFER, DISTRIBUTION OR MODIFICATION OF
 * PART OR ALL OF THE CODE IN ANY FORM WITHOUT THE PRIOR WRITTEN PERMISSION OF ZEB/INFORMATION.TECHNOLOGY IS PROHIBITED.
 *
 * created: 09.03.2023 - 07:52:27
 */
package de.zeb.lowcode.model.domain;


/**
 * @author dkleine
 *
 */
public enum Datentyp {
    ID, TEXT, GANZZAHL, PROZENTZAHL, GELD_BETRAG, BASISPUNKT, ZAHL, BOOLEAN, TEXT_JN, DATUM, ZEITSTEMPEL, ENTITAET, URL,
    ZEITPUNKT_LETZTE_AENDERUNG, ZEITPUNKT_ERSTELLUNG, ERSTELLT_VON, MODIFIZIERT_VON, VERSION
}
